### ISSUE TITLE
Failed to execute goal com.spotify:docker-maven-plugin:1.2.2:build (build-image) on project mall-admin: Exception caught

### ISSUE THREAD

**Issue by lancwl418** [macrozheng/mall-learning#100]
你好，我试着去运行maven package 命令。但是出现了以下报错。

Failed to execute goal com.spotify:docker-maven-plugin:1.2.2:build (build-image) on project mall-admin: Exception caught

请问有人遇到这个情况么？

**Comment by BeastMachines** [comment]
+1
