### ISSUE TITLE
关于 mall-tiny-01 的 MyBatis-Generator 部分

### ISSUE THREAD

**Issue by EricSUID** [macrozheng/mall-learning#102]
环境: MySQL5.7 

generator.properties 配置:
- `jdbc.connectionURL` 可能需要在结尾增加 `useSSL=false` 

> 否则可能出现 `Exception getting JDBC Driver` 异常

**Comment by LittleTheFu** [comment]
我修改的是 application.yml 里面的对应行，才使得项目可以正确运行
![无标题](https://user-images.githubusercontent.com/15071167/126732331-7e6bf158-f033-4381-ab96-36ccb41c8200.png)

**Comment by LittleTheFu** [comment]
我修改的是  apllication.yml 文件，解决了这个问题
![无标题](https://user-images.githubusercontent.com/15071167/126732896-5c3c4a80-0fbc-4975-8d02-750bb83f027c.png)
