### ISSUE TITLE
Star 数量级应该是 2k+

### ISSUE THREAD

**Issue by ShuuutUpandDance** [macrozheng/mall-learning#12]
项目描述里的 Star 数量的数量级现在写的是 20k+，事实上应该是 2k+

**Comment by WWS321** [comment]
项目描述里说的 **mall 项目** 是这个 [](https://github.com/macrozheng/mall) 。
而当前这个是整个 **mall 项目** 的教学项目，叫做 **mall-learning** 。

**Comment by WWS321** [comment]
> 项目描述里的 Star 数量的数量级现在写的是 20k+，事实上应该是 2k+
项目描述里说的 **mall 项目** 是这个 [](https://github.com/macrozheng/mall) 。
而当前项目是整个 **mall 项目** 的教学项目，叫做 **mall-learning** 。

**Comment by WWS321** [comment]
项目描述里说的 **mall 项目** 是这个 https://github.com/macrozheng/mall ，Star 数确实有 20k+。
而当前项目是整个 **mall 项目** 的教学项目，叫做 **mall-learning** 。
