### ISSUE TITLE
用户和角色的关联，在代码中有处理吗

### ISSUE THREAD

**Issue by luwu1991** [macrozheng/mall-learning#14]
用户和角色的绑定，在代码中有处理吗？还是直接在关系表中生成的，没有处理这块的逻辑

**Comment by zhtime** [comment]
我也在用着项目尝试，后台我是按照他的文档一步步打下来的，后台管理页面我是git下来直接用的，我的问题所在就是，我尝试着连接自己的后台去登陆后台管理页面，却发现登陆不上去，页面报：用户名或密码错误，我去公众号拿到了账号发现还是不行，看了下控制台，http://lcoalhost:8080/admin/inform报404，前台的页面也是没有的，我个人认为也就是我后台contorller层中根本没有这个api所以不可能登陆的上去，到这一步也就为止了。我试了一下他线上部署的后台服务器，倒是可以登陆，我也git下来他的后台Api但是也没有发现有，上面的报404的接口。。。
