### ISSUE TITLE
添加Swagger-UI的配置代码示例有点小瑕疵

### ISSUE THREAD

**Issue by cjs12** [macrozheng/mall-learning#19]
## [文档地址](https://macrozheng.gitee.io/mall-learning/#/architect/mall_arch_02?id=%e6%b7%bb%e5%8a%a0swagger-ui%e7%9a%84%e9%85%8d%e7%bd%ae)

![image](https://user-images.githubusercontent.com/36249835/68933109-f303ee80-07ce-11ea-87e3-37e30053237c.png)

这个注释有点小问题，个人测试的实际情况是。
```java
//为有@ApiOperation注解的方法生成API文档
.apis(RequestHandlerSelectors.withMethodAnnotation(ApiOperation.class))
```
上述代码仅扫描  **类上有无指定注解**，
即如果`类上`有ApiOperation注解，会生成API文档。
又因为该注解只能在作用于方法。建议删除此逻辑。

**Comment by macrozheng** [comment]
这个只是一个示例，为了方便说明三种不同的生成APIw文档的规则，平时只需用一种即可。
