### ISSUE TITLE
admin初始密码

### ISSUE THREAD

**Issue by wlnirvana** [macrozheng/mall-learning#21]
请问`mall.sql`和`mall_tiny.sql`中的`admin`初始密码`'$2a$10$NZ5o7r2E.ayT2ZoxgjlI.eJ6OEYqjH7INR/F.mXDbjZJi9HF0YCVG'`是什么呀？好像没有在相关文档里面看到。

**Comment by wlnirvana** [comment]
微信号回复的`macro123`貌似不对，登录不进去。手动hack成了`admin`，加密后数据库里面是`$2a$10$XGtR3Z/XWVyiWgjOmIWD3OaVo.YLC2VaI7eBxDC3QaPvc2ketTZ62`，可以登录了。

**Comment by llkoio** [comment]
123456
