### ISSUE TITLE
/cart/add

### ISSUE THREAD

**Issue by llkoio** [macrozheng/mall-learning#24]
postman请求
http://localhost:8085/mall-gateway/cart/add
总是：
{
    "code": 401,
    "data": "Full authentication is required to access this resource",
    "message": "暂未登录或token已经过期"
}

请求体：
{
  "createDate": "2019-12-21T12:25:16.428Z",
  "deleteStatus": 0,
  "id": 0,
  "memberId": 0,
  "memberNickname": "string",
  "modifyDate": "2019-12-21T12:25:16.428Z",
  "price": 0,
  "productAttr": "string",
  "productBrand": "string",
  "productCategoryId": 0,
  "productId": 0,
  "productName": "string",
  "productPic": "string",
  "productSkuCode": "string",
  "productSkuId": 0,
  "productSn": "string",
  "productSubTitle": "string",
  "quantity": 0,
  "sp1": "string",
  "sp2": "string",
  "sp3": "string"
}

**Comment by mars6666** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                821105360
                            
                    
                        
                            
                                    821105360@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 1/5/2020 15:19，macro<notifications@github.com> wrote： 


Closed #24.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
