### ISSUE TITLE
Could not find artifact com.macro.mall:mall-mbg:pom:1.0-SNAPSHOT

### ISSUE THREAD

**Issue by sunlight2728** [macrozheng/mall-learning#27]
照着文档 package 构建mall-admin 项目的时候出现这个问题
Could not find artifact com.macro.mall:mall-mbg:pom:1.0-SNAPSHOT

**Comment by COOLMSF** [comment]
> 照着文档 package 构建mall-admin 项目的时候出现这个问题
> Could not find artifact com.macro.mall:mall-mbg:pom:1.0-SNAPSHOT

same problem

**Comment by ForsythiaSuspensa** [comment]
same problem
