### ISSUE TITLE
UnsatisfiedDependencyException

### ISSUE THREAD

**Issue by wyp2019** [macrozheng/mall-learning#64]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'pmsBrandController': Unsatisfied dependency expressed through field 'brandService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'pmsBrandServiceImpl': Unsatisfied dependency expressed through field 'brandMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'pmsBrandMapper' defined in file [F:\IDEA\firstproject\mall-master\mall-tiny-01\target\classes\com\macro\mall\tiny\mbg\mapper\PmsBrandMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory';

**Comment by XinZheng-SH** [comment]
我也碰到这个问题了，没法解决，跑源代码一样
