### ISSUE TITLE
redis那个是走了jedis的连接池吗？

### ISSUE THREAD

**Issue by pigzwy** [macrozheng/mall-learning#65]
![image](https://user-images.githubusercontent.com/50192984/89854222-eaa5dc00-dbc5-11ea-82e6-2f2c35a55128.png)

**Comment by macrozheng** [comment]
用的是Lettuce，具体可以参考[Spring Data Redis 最佳实践！](http://www.macrozheng.com/#/reference/spring_data_redis)
