### ISSUE TITLE
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter] with root cause

### ISSUE THREAD

**Issue by jesse996** [macrozheng/mall-learning#74]
如题，04报错

**Comment by jesse996** [comment]
解决了，加下面两个依赖
`<dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.0</version>
</dependency>

<dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <version>2.3.1</version>
`</dependency>``

**Comment by cactusc9** [comment]
你好，请问你是怎么知道需要这两个包的啊？
解决思路是怎样的啊

**Comment by cactusc9** [comment]
你好，请问你是怎么知道需要这两个包的啊？
解决思路是怎样的啊

**Comment by jesse996** [comment]
> 你好，请问你是怎么知道需要这两个包的啊？
> 解决思路是怎样的啊

谷歌
