### ISSUE TITLE
微服务权限终极解决方案，Spring Cloud Gateway + Oauth2 实现统一认证和鉴权！invalid_client

### ISSUE THREAD

**Issue by qianshun** [macrozheng/mall-learning#77]
对着 微服务权限终极解决方案，Spring Cloud Gateway + Oauth2 实现统一认证和鉴权！ 做：
获取token报错：
{
    "error": "invalid_client",
    "error_description": "Bad client credentials"
}

**Comment by macrozheng** [comment]
client_id和client_secret弄错了吧，具体参考[《微服务权限终极解决方案，Spring Cloud Gateway + Oauth2 实现统一认证和鉴权！》](http://www.macrozheng.com/#/cloud/gateway_oauth2)
