### ISSUE TITLE
传入错误的token不拦截

### ISSUE THREAD

**Issue by nyhitany** [macrozheng/mall-learning#79]
JwtAuthenticationTokenFilter过滤器类 的该行代码String username = jwtTokenUtil.getUserNameFromToken(authToken);
当传入一个错误的token时，进行token校验会抛出异常，但是我看了代码里面进行了异常捕获，继续往下返回了一个空的username，然后代码空值时继续往下执行。过滤器是不是就直接放行了，应该对外抛出异常吧。

 /**
     * 从token中获取JWT中的负载
     *
     */
    private Claims getClaimsFromToken(String token) {
        Claims claims = null;
        try {
            claims = Jwts.parser()
                    .setSigningKey(secret)
                    .parseClaimsJws(token)
                    .getBody();
        } catch (Exception e) {
            LOGGER.info("JWT格式验证失败:{}", token);//需要抛出异常
        }
        return claims;
    }

**Comment by macrozheng** [comment]
JwtAuthenticationTokenFilter中有一行很关键的代码，当username不为空时会向SpringSecurity的Context设置认证信息。

```java
SecurityContextHolder.getContext().setAuthentication(authentication);
```

如果没有认证信息的话，在接下来的认证过滤器中是无法通过的，实际会返回如下信息。

```json
{
  "code": 401,
  "data": "Full authentication is required to access this resource",
  "message": "暂未登录或token已经过期"
}
```
