### ISSUE TITLE
建议部署文档增加一点点说明

### ISSUE THREAD

**Issue by xiumu2017** [macrozheng/mall-learning#82]
[http://www.macrozheng.com/#/deploy/mall_deploy_docker_compose?id=elasticsearch-1](http://www.macrozheng.com/#/deploy/mall_deploy_docker_compose?id=elasticsearch-1)
需要安装中文分词器IKAnalyzer，并重新启动。（需要替换链接中的版本号为当前ELK的版本号）

Plugin [analysis-ik] was built for Elasticsearch version 6.4.0 but version 7.6.2 is running

**Comment by macrozheng** [comment]
已更正
