### ISSUE TITLE
UmsAdminRoleRelationDao 的mapper 是怎么生成的呢？

### ISSUE THREAD

**Issue by JiajunWong** [macrozheng/mall-learning#83]
大佬们，

请问`UmsAdminRoleRelationDao` 的 `resources/mapper/UmsAdminRoleRelationDao.xml` 是怎么生成的呢？

当我run app时候有这个错误：

> Field adminRoleRelationDao in com.sopherwang.mall.service.impl.UmsAdminServiceImpl required a bean of type 'com.sopherwang.mall.dao.UmsAdminRoleRelationDao' that could not be found.

感谢感谢。

**Comment by niuzaiku** [comment]
复制过去之后，记得加上

`@MapperScan({"com.macro.mall.tiny.mbg.mapper","com.macro.mall.tiny.dao"})`

**Comment by macrozheng** [comment]
xxxDao.xml这些文件都是手写的。
