### ISSUE TITLE
无法自动装配。未找到 'PmsBrandMapper' 类型的 Bean。

### ISSUE THREAD

**Issue by wqqwqq666** [macrozheng/mall-learning#85]
项目报错
![图片](https://user-images.githubusercontent.com/15796964/111108826-910af300-8594-11eb-86f0-63bd2dc54566.png)

**Comment by zWaNg3** [comment]
找到这个mapper然后在上边添加@Mapper注解

**Comment by solidSpoon** [comment]
![image](https://user-images.githubusercontent.com/39454841/116041056-57eb9580-a69f-11eb-9171-46d9fabf2aef.png)

我也有这个问题，发现是 PmsBrandMapper.xml 里面生成了重复的内容，这个文件是 mbg.Generator.java 自动生成的，将这个文件删除后重新生成一份就好了
