### ISSUE TITLE
JwtAuthenticationTokenFilter验证逻辑

### ISSUE THREAD

**Issue by yyl4ever** [macrozheng/mall-learning#9]
你好，在 mall-tiny-04 节，JwtAuthenticationTokenFilter 类，有一处代码感到疑惑：
![image](https://user-images.githubusercontent.com/23069118/63753970-a4893700-c8e6-11e9-9a44-56d7235c8a78.png)

`if (jwtTokenUtil.validateToken(authToken, userDetails)) `，其中，
 authToken 和 userDetails 源头是一致的，都是来自 Authorization，那这个比较在不过期的情况下，肯定返回 true，只是用来判断过期吗？另外，signature 的作用体现在哪里？为什么随便造  token 中的 signature 也能登录成功呢？方便的话能解答一下，谢谢~

**Comment by macrozheng** [comment]
主要是为了判断token是否还有效

**Comment by yyl4ever** [comment]
谢谢，但是 signature 在哪里起作用的？方便解答一下嘛？
